nama	= input("Nama\t\t\t: ") 
nim	= input("NIM\t\t\t: ") 
kelas	= input("Kelas Pararel\t\t: ") 
ttl	= input("Tempat/Tanggal Lahir\t: ") 
alamat	= input("Alamat\t\t\t: ") 
hobby	= input("Hobby\t\t\t: ") 
nohp	= input("No. HP\t\t\t: ") 

print("")
print("Nama\t\t\t:", nama)
print("NIM\t\t\t:", nim)
print("Kelas Paralel\t\t:", kelas)
print("Tempat/Tanggal Lahir\t:", ttl)
print("Alamat\t\t\t:", alamat)
print("Hobby\t\t\t:", hobby)
print("No. HP\t\t\t:", nohp)